version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:8081"
    networks:
      - default

  tg_bot:
    build: .
    container_name: tg_bot
    restart: always
    depends_on:
      - mongodb
    networks:
      - default

networks:
  default:
    driver: bridge